config/routes.rb
Rails.application.routes.draw do

  root to: "welcome#index"
  resources :addresses
  resources :products
  resources :categories
  # resources :categories do
  #   resources :products, on: :members
  # end

  get "/users", to: "users#index"
  get "/user/:id", to: "users#show"
  
  

  devise_for :users, controllers: {registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address <  ActiveRecord::Base
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :products, dependent: :destroy
    validates :title, :description,
    presence: true,
    length: { minimum: 5 }
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "400x400>", thumb: "100x100>", large: "500x500>"}, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    belongs_to :category   
    validates :category_id, presence: true
    validates :description, length: {maximum: 255}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :address
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end
  
  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)
    @address.user_id = current_user.id
    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:title, :city, :street, :home)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :initialize_categories
	def initialize_categories
	  @categories = Category.all
	end
  

  def check_admin
    redirect_to root_url unless current_user && current_user.admin? 
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, except:[:index, :show]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @categories = Category.all
  end
  

  def show
    @products = Product.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

 
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new 
    end
  end

  def destroy
      @category.destroy
      redirect_to @category  
  end

  def update
    @category.update(category_params)
    redirect_to @category
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_admin, except:[:index, :show]


  def index
    @categories = Category.all    
  end

  def show
    @categories = Category.all
  end

  def new
    @product = Product.new
  end

  def edit
  end

 
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new 
    end
  end

  def destroy
    @product.destroy  
    redirect_to @product
  end

  def update
    @product.update(product_params)
    redirect_to @product
  end
  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :discount, :category_id, :image)
    end
end

app/controllers/registrations_controller.rb
class  RegistrationsController < Devise::RegistrationsController
	private
	  def sign_up_params
	    params.require(:user).permit(:phone,:email,:password,:password_confirmation)
	  end

	  def account_update_params
	    params.require(:user).permit(:name,:lastname,:age,:gender,:current_password)
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :check_admin, except:[:index]


  def index
    @users = User.all    
  end

  def show
  end

  
  def destroy
    @user.destroy  
    redirect_to @user
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_active?(link_path)
	 current_page?(link_path) ? "active" : ""
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :address_title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, id: :address_city, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :street %>
    <%= form.text_field :street, id: :address_street, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :home %>
    <%= form.text_field :home, id: :address_home, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>
<div class="col-md-4">
<%= render 'form', address: @address %>
<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>
</div>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Мои адреса</h1>
<div class="col-md-8">
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Название</th>
      <th>Город</th>
      <th>Улица</th>
      <th>Дом</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.title %></td>
        <td><%= address.city %></td>
        <td><%= address.street %></td>
        <td><%= address.home %></td>
        <td><%= link_to 'Открыть', address %></td>
        <td><%= link_to 'Редактировать', edit_address_path(address) %></td>
        <td><%= link_to 'Удалить', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Address', new_address_path %>
</div>

app/views/addresses/new.html.erb
<h1>New Address</h1>
<div class="col-md-4">
<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>
</div>

app/views/addresses/show.html.erb
  <p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @address.title %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>Home:</strong>
  <%= @address.home %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/application/_hor_menu.html.erb
<ul class="nav nav-pills nav-stacked" style="background-color: white; 
border-radius: 3%;
box-shadow: 0 0 5px rgba(0,0,0,0.3);">
    <% @categories.each do |cat| %>
	    <li class="<%= is_active?(cat) %>"><%= link_to cat.title, cat %></li>
	<%end%>            

app/views/application/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Cake Store", root_path, class:"navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <% if user_signed_in? && current_user.admin?%>      
        <li><%= link_to "New product", new_product_path%></li>
        <li><%= link_to "New category", new_category_path%></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
                <li> <%= link_to "Личный кабинет", edit_user_registration_path %></li>                
                <li> <%= link_to "Выход", destroy_user_session_path, :method => 'delete' %></li>
            <% else %>
                <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <% end%>
            
    </ul>
  </div>
</nav>

app/views/categories/_form.html.erb
<div class="col-md-4">

<%= form_for @category do |form|%>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :category_description , class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', :class => 'btn btn-default' %>
  </div>
<% end %>
</div>

app/views/categories/edit.html.erb
<h1>Edit category</h1>
<%= render "form"%>

app/views/categories/index.html.erb
<h1>Categories</h1>
<% @categories.each do |category| %>
    <%= link_to category.title, category %></li>
<% end %>

app/views/categories/new.html.erb
<h1> New category </h1>
<%= render "form"%>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>
<% if user_signed_in? and current_user.admin?%>
<%= link_to 'Удалить', @category, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Изменить', edit_category_path(@category) %> |
<%= link_to 'Добавить продукт', new_product_path(:cat_id => @category.id) %>
<%end%>
    <% @category.products.in_groups_of(3,false).each do |group| %>
        <div class="row">
            <% group.each do |product| %>
                <div class="col-md-4">
                <div class="text-block product-card">
                    <%= image_tag product.image.url(:medium), class:"figure-img img-fluid rounded " %>
                    <div class="product-card-meta">
                        <figcaption class="figure-caption "> 
                            <%= link_to product.title , product_path(product) %>  
                        </figcaption>
                        <h3><span class="label label-success product-price"><%= product.price%> тг</span> </h3>
                    </div>   
                </div>
                </div>
            <% end %>
        </div>
    <% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Cstore</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
    <div class="container">
        <div class="row">
            <%= render :partial => 'nav'%>
        </div>
        <div class="row">
            <div class="col-md-2">
                <%= render :partial => 'hor_menu'%>
            </div>
            <div class="col-md-10">
                <%= yield %>
            </div>
        </div>
    </div>
</body>

</html>

app/views/products/_form.html.erb
<div class="col-md-7">
<%= form_for @product do |form|%>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title, class:"form-control" %>
  </div>
  
  
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :discount %>
    <%= form.text_field :discount, id: :product_discount, class:"form-control" %>
  </div>

<div class="field">
    <%= form.label :category_id %>
      <%= form.select :category_id, Category.all.collect { |c| [ c.title, c.id ] },
       include_blank: true, class:"form-control", :selected => params[:cat_id]%>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :product_image %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', :class => 'btn btn-default' %>
  </div>

<% end %>


</div>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<div class="row">

    <%= render 'form'%>

<div class="col-md-3">
    <div class="product-image">
        <%= image_tag @product.image.url(:medium) %>
    </div>
</div>
</div>
  

app/views/products/index.html.erb
<h1>Products</h1>

<% @categories.each do |category| %>
    <h3><%= category.title %></h3>
    <% category.products.in_groups_of(3,false).each do |group| %>
        <div class="row">
            <% group.each do |product| %>
                <div class="col-lg-4 text-block">
                    <figure class="figure">
                        <%= image_tag product.image.url(:medium), class:"figure-img img-fluid rounded center-block" %>
                        <figcaption class="figure-caption text-center"> <%= link_to product.title , product_path(product) %>    </figcaption>
                    </figure>
                </div>
            <% end %>
        </div>
    <% end %>
<%end%>

app/views/products/new.html.erb
<h1>New product</h1>
 <%= render "form" %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<div class="row main">
<div class="col-md-5">
    <p>
    <%= image_tag @product.image.url(:medium), class:"product-image" %>
    </p>
</div>
<div class="col-md-7">
    <h4 class="product-title">
      <%= @product.title %>
    </h4>
  
    <h5> Цена:
    <span class="label label-success product-price">
      <%= @product.price %> тг
    </span>
    </h5>

    <% if @product.discount!=0 %>
      <h3><span class="label label-danger">СКИДКА:
        <%= @product.discount %> %
        </span>
      </h3>
    <% end %>

<div>
  <div class="panel panel-default">
      <div class="panel-heading">Описание</div>
      <div class="panel-body">
        <p>
          <%= @product.description %>
        </p>
      </div>
    </div>
 </div>
 <div>
<% if user_signed_in? && current_user.admin?%>
    <%= link_to 'Редактировать', edit_product_path(@product) %> |
    <%= link_to 'Удалить', @product, method: :delete, data: { confirm: 'Are you sure?' } %>
 <% end %>
 </div>
</div>

 </div>

app/views/users/index.html.erb
<table class="table table-stripped">
  <thead>
    <tr>
    <th>Name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Телефон</th>
    <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%=user.name%></td>
      <td><%=user.lastname%></td>
      <td><%=user.email%></td>
      <td><%=user.phone%></td>
      <td><%= link_to 'Открыть', "show/#{user.id}" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<p>
  <strong>Имя:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Фамилия:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Почта:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Телефон:</strong>
  <%= @user.phone %>
</p>